#!/bin/bash

if [ "$DEBUG" == "true" ]; then
  env | sort
fi

cd /src/${BUILD_CODE}${BUILD_PATH}

if [ "$DEBUG" == "true" ]; then
  echo docker build --build-arg REPOSITORY=$REPOSITORY --build-arg REGISTRY=$REGISTRY --build-arg TAG=${TAG:-latest} -t $IMAGE_NAME -f $DOCKERFILE_PATH .
fi

docker build --build-arg REPOSITORY=$REPOSITORY --build-arg REGISTRY=$REGISTRY --build-arg TAG=${TAG:-latest} -t $IMAGE_NAME -f $DOCKERFILE_PATH .
