#!/bin/bash
env

cd /src/${BUILD_CODE}${BUILD_PATH}
pwd
echo docker build --build-arg REPOSITORY=$REPOSITORY --build-arg TAG=$TAG -t $IMAGE_NAME -f $DOCKERFILE_PATH .

docker build --build-arg REPOSITORY=$REPOSITORY --build-arg TAG=$TAG -t $IMAGE_NAME -f $DOCKERFILE_PATH .
